### ISSUE TITLE
Replace with Enum.TryParse

### ISSUE THREAD

**Issue by inayelle** [smartTigerCode98/CSharp_NoteSystem#5]
https://github.com/smartTigerCode98/CSharp_NoteSystem/blob/56202a932a70b23a9e9c5ffe2114f45bf994afd0/App/Controllers/SignController.cs#L38
___
No need in list of commands, replace command detection with Enum.TryParse

**Comment by smartTigerCode98** [comment]
Do I need to change my static class to enum?

**Comment by inayelle** [comment]
Yes
